# Site settings
title: Thank you for everything you've done for us Google Open Source Team
email: your-email@domain.com
url: https://example.github.io
description: "Thank you for hosting Google Code-in for 10 years and spreading the word to teenagers like us the word about Open Source and how important it is."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: The Google Code-in winners you met during the years

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: GitHub
    url: https://twitter.com/SBootstrap

collections:
  winners:
    sort_by: name
  
# Build settings
markdown: kramdown
permalink: pretty
